### ISSUE TITLE
not saving shrec_net.pth after dynamic training 

### ISSUE THREAD

**Issue by NandhaKishorM** [ofnote/gestop#1]
After dynamic training the shrec_net.pth is not saved in models directory. and also the user_net.pth is not as a zip file?

**Comment by sriramsk1999** [comment]
Hi @kishorkuttan , it appears you started using this repo just before I could fully migrate the changes :) Could you get the latest commits and see if the issue persists?

To answer your question, `.pth` files are not zip files. `.pth` is the convention used to denote a saved PyTorch model.

**Comment by NandhaKishorM** [comment]
Its working great. Trained it on torch 1.4.0 and torchvision 0.5.0. Now its working. You can close the thread

**Comment by sriramsk1999** [comment]
Awesome :)
