### ISSUE TITLE
Issues with receiver step

### ISSUE THREAD

**Issue by Vanpersie1894** [ofnote/gestop#11]
Hi. This is great work and I was trying to replicate the same for further use. However, after installing all the dependencies from 'requirements.txt', when I try to execute the server step: 'python3 -m gestop.receiver' , the operation stalls in Loading StaticNet and Dynamic Net and doesn't go any further. Is there an additional dependency I am missing? Some help would be awsome! Thanks in advance

**Comment by sriramsk1999** [comment]
Thanks for raising the issue. After loading the StaticNet and DynamicNet, the receiver is ready to be used, so you can move on to the next step and start the client. I've added a log statement to directly indicate that the receiver is ready to clear up any confusion.

**Comment by Vanpersie1894** [comment]
Hey again. Thank you for your swift response and adding the log command. But that does not seem to be a problem on my side. The receiver won't move further after execution of server step. It just stalls in loading process. Do I have to load anything else additionally apart from the wiki requirements? The binding seem to not be working as your recently added log command still won't show up. Attaching screenshot for the step. Thanks again in advance!
![Screenshot from 2021-04-01 12-16-15](https://user-images.githubusercontent.com/81721359/113280908-376d2d00-92e5-11eb-86c6-bf4ded3ce596.png)

**Comment by sriramsk1999** [comment]
1. Are you sure you have the latest master code? There is nothing happening after "Loading DynamicNet" and where "Receiver is ready" should come, other than initializing the socket.
2. The receiver isn't stalling, the only two things to load are the StaticNet and the DynamicNet. After that, the receiver is ready to be used, and you can go ahead and start the client with `python -m gestop.keypoint_gen.hand_tracking`

**Comment by Vanpersie1894** [comment]
Hi. I was missing the xdotool and did clone the latest master. It works fine now! I apologize for the last reply but now with the user knowing that it is ready, the client can be started in a new window. Thank you and great work again :) I will close this now.
