### ISSUE TITLE
Architecture Comparison

### ISSUE THREAD

**Issue by Praveen1803** [ofnote/gestop#12]
Hey! The program works well for me with a slight latency though. I went through the forwarded paper hoping to get some insights on possible comparative studies/comparisons with known architectures but unfortunately could not find any. Can you please tell if you did relative comparisons with any baseline? 

Thanks in advance!

Best,
PM

**Comment by ekshaks** [comment]
Praveen, the space of different architectures used for static and dynamic gestures is vast -- you can go through some of papers mentioned in the related work section. The focus here is to build an end-to-end tool and the challenges there.

Let us know if you have any specific questions about any of the architectures. Also, we welcome pull requests -- please feel free to implement other architectures for gesture recognition in gestop and let us know your results.

**Comment by Praveen1803** [comment]
Hello Nishant, apologies for my late reply. I understand that the focus is to build a comprehensive tool but was interested in knowing other performances as we are trying to use Media Pipe to complete a project in H.M.I. as well. I will definitely try to implement other architectures and let you know if improvement is found.
Best.
