### ISSUE TITLE
daataset of dynamic gestures

### ISSUE THREAD

**Issue by fengyang1997** [ofnote/gestop#36]
Hello, the dataset of dynamic_gestures only have one gesture:'cycle', can you share all gestures?

**Comment by sriramsk1999** [comment]
Hi @fengyang1997 , the dynamic gestures on google drive is only an example of what it would look like if you captured more data on your own. All the other gestures come from the [SHREC2017 dataset](http://www-rech.telecom-lille.fr/shrec2017-hand/)

**Comment by fengyang1997** [comment]
Ok, thanks for your reply.
